// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqqyxknWG0rzBO2jAnqCfsBk-2pqVrTrY',
    appId: '1:669611315079:web:01158955a81caaf5894d22',
    messagingSenderId: '669611315079',
    projectId: 'flutter-party-cf1f3',
    authDomain: 'flutter-party-cf1f3.firebaseapp.com',
    storageBucket: 'flutter-party-cf1f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI2X4_93fM8CBX5Em6Iw9K3kYo2vXK1Po',
    appId: '1:669611315079:android:3432e5344ae1dd53894d22',
    messagingSenderId: '669611315079',
    projectId: 'flutter-party-cf1f3',
    storageBucket: 'flutter-party-cf1f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhmBbLl6HyYR_w8mE20DxEdOV2htF-qM',
    appId: '1:669611315079:ios:ad698d2219b90f0f894d22',
    messagingSenderId: '669611315079',
    projectId: 'flutter-party-cf1f3',
    storageBucket: 'flutter-party-cf1f3.appspot.com',
    iosBundleId: 'com.example.partyOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhmBbLl6HyYR_w8mE20DxEdOV2htF-qM',
    appId: '1:669611315079:ios:e522e1d28035d4f7894d22',
    messagingSenderId: '669611315079',
    projectId: 'flutter-party-cf1f3',
    storageBucket: 'flutter-party-cf1f3.appspot.com',
    iosBundleId: 'com.example.partyOrganizer.RunnerTests',
  );
}
